[package]
name = "binetic-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tracing = "0.1"
bytes = "1"
mmap = "0.1"
parking_lot = "0.12"
once_cell = "1"
sha2 = "0.10"
hmac = "0.12"
crossbeam = "0.8"

[dev-dependencies]
rand = "0.8"
criterion = "0.5"
